import { site } from "./site";

// Keep the visible answers and structured data aligned from one source.
export const buyingQuestions = [
  { id: "supplier", question: "What does ESCU supply in Nepal?", answer: "Everest Super Chemical Udhyog (ESCU) manufactures and supplies water treatment chemicals, swimming pool chemicals, and housekeeping and cleaning products from Kathmandu. The range also includes cooking fuel, machine oils and test kits. ESCU manufactures some products and imports others directly.", href: "/products", link: "Browse the product catalogue" },
  { id: "quote", question: "How do I request a wholesale chemical quote?", answer: "Send the product name, required quantity, preferred pack size, delivery location and required date. ESCU can then check availability, current pricing and delivery arrangements for your order. Use the quote form, WhatsApp or telephone.", href: "/quote", link: "Request a wholesale quote" },
  { id: "prices", question: "Where can I find chemical prices and minimum order quantities?", answer: "ESCU quotes prices on request rather than publishing a fixed online price list. Ask for the current price, available pack sizes and minimum order quantity for the specific product and quantity you need. A catalogue listing does not confirm current stock.", href: "/quote", link: "Ask about pricing and quantities" },
  { id: "delivery", question: "Does ESCU deliver outside Kathmandu?", answer: "ESCU supplies businesses across Nepal from Kathmandu. Share your delivery location and required date so the team can confirm delivery options, charges and timing before you place an order.", href: "/contact", link: "Discuss delivery with ESCU" },
  { id: "specifications", question: "What product details should I confirm before ordering?", answer: "Confirm the exact product name, intended application, required grade or concentration, pack size and quantity with the team. Request the relevant product specifications and safety data sheet, and confirm which documents are available for that product before ordering.", href: "/products", link: "Find your product" },
  { id: "customers", question: "Which businesses does ESCU supply?", answer: "ESCU serves hotels, resorts, hospitals, water treatment plants, swimming pools, industrial plants, restaurants, commercial buildings and engineering projects. Send the requirements for your operation to discuss wholesale or repeat supply.", href: "/industries", link: "Explore the industries served" },
  { id: "location", question: "Where is ESCU located and when can I contact the team?", answer: `Visit ESCU at ${site.address}. Business hours are ${site.hours}. Call ${site.phone} or email ${site.email}.`, href: "/contact", link: "View contact details and map" },
];
